In [1]:
import os


In [2]:
os.getcwd()

'c:\\Users\\HPr\\Restaurant_Rating_prediction\\notebook'

In [3]:
os.chdir("c:\\Users\\HPr\\Restaurant_Rating_prediction")


In [4]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [5]:
import pandas as pd
csv_file_path=r"C:\Users\HPr\Restaurant_Rating_prediction\RestaurantRating\artifact\data_ingestion\2023-01-11-17-12-28\raw_data\zom.csv"
RestaurantRating_data_frame=pd.read_csv(csv_file_path)

In [6]:
RestaurantRating_data_frame.head(12)

Restaurant ID                           Restaurant_Name  Country Code  \
0         6317637                          Le Petit Souffle           162   
1         6304287                          Izakaya Kikufuji           162   
2         6300002                    Heat - Edsa Shangri-La           162   
3         6318506                                      Ooma           162   
4         6314302                               Sambo Kojin           162   
5        18189371                              Din Tai Fung           162   
6         6300781                                Buffet 101           162   
7         6301290                                   Vikings           162   
8         6300010  Spiral - Sofitel Philippine Plaza Manila           162   
9         6314987                                  Locavore           162   
10        6309903                          Silantro Fil-Mex           162   
11        6309455           Mad Mark's Creamery & Good Eats           162   

                City                                            Address  \
0        Makati City  Third Floor, Century City Mall, Kalayaan Avenu...   
1        Makati City  Little Tokyo, 2277 Chino Roces Avenue, Legaspi...   
2   Mandaluyong City  Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...   
3   Mandaluyong City  Third Floor, Mega Fashion Hall, SM Megamall, O...   
4   Mandaluyong City  Third Floor, Mega Atrium, SM Megamall, Ortigas...   
5   Mandaluyong City  Ground Floor, Mega Fashion Hall, SM Megamall, ...   
6         Pasay City  Building K, SM By The Bay, Sunset Boulevard, M...   
7         Pasay City  Building B, By The Bay, Seaside Boulevard, Mal...   
8         Pasay City  Plaza Level, Sofitel Philippine Plaza Manila, ...   
9         Pasig City  Brixton Technology Center, 10 Brixton Street, ...   
10        Pasig City       75 East Capitol Drive, Kapitolyo, Pasig City   
11        Pasig City       23 East Capitol Drive, Kapitolyo, Pasig City   

                                           Locality  \
0         Century City Mall, Poblacion, Makati City   
1        Little Tokyo, Legaspi Village, Makati City   
2        Edsa Shangri-La, Ortigas, Mandaluyong City   
3            SM Megamall, Ortigas, Mandaluyong City   
4            SM Megamall, Ortigas, Mandaluyong City   
5            SM Megamall, Ortigas, Mandaluyong City   
6   SM by the Bay, Mall of Asia Complex, Pasay City   
7   SM by the Bay, Mall of Asia Complex, Pasay City   
8       Sofitel Philippine Plaza Manila, Pasay City   
9                                         Kapitolyo   
10                                        Kapitolyo   
11                                        Kapitolyo   

                                     Locality Verbose         lon        lat  \
0   Century City Mall, Poblacion, Makati City, Mak...  121.027535  14.565443   
1   Little Tokyo, Legaspi Village, Makati City, Ma...  121.014101  14.553708   
2   Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...  121.056831  14.581404   
3   SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.056475  14.585318   
4   SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.057508  14.584450   
5   SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.056314  14.583764   
6   SM by the Bay, Mall of Asia Complex, Pasay Cit...  120.979667  14.531333   
7   SM by the Bay, Mall of Asia Complex, Pasay Cit...  120.979333  14.540000   
8   Sofitel Philippine Plaza Manila, Pasay City, P...  120.980090  14.552990   
9                               Kapitolyo, Pasig City  121.056532  14.572041   
10                              Kapitolyo, Pasig City  121.057916  14.567689   
11                              Kapitolyo, Pasig City  121.060820  14.570849   

                              Cuisines  ...          Currency  \
0           French, Japanese, Desserts  ...  Botswana Pula(P)   
1                             Japanese  ...  Botswana Pula(P)   
2     Seafood, Asian, Filipino, Indian  ...  Botswana Pula(P)   
3        

In [7]:
RestaurantRating_data_frame['Rating'].shape


(9551,)

In [8]:
RestaurantRating_data_frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Restaurant ID         9551 non-null   int64  
 1   Restaurant_Name       9551 non-null   object 
 2   Country Code          9551 non-null   int64  
 3   City                  9551 non-null   object 
 4   Address               9551 non-null   object 
 5   Locality              9551 non-null   object 
 6   Locality Verbose      9551 non-null   object 
 7   lon                   9551 non-null   float64
 8   lat                   9551 non-null   float64
 9   Cuisines              9542 non-null   object 
 10  cost_for_two          9551 non-null   int64  
 11  Currency              9551 non-null   object 
 12  Has Table booking     9551 non-null   object 
 13  Has Online delivery   9551 non-null   object 
 14  Is delivering now     9551 non-null   object 
 15  Switch to order menu 

In [9]:
RestaurantRating_data_frame.describe()

Restaurant ID  Country Code          lon          lat   cost_for_two  \
count   9.551000e+03   9551.000000  9551.000000  9551.000000    9551.000000   
mean    9.051128e+06     18.365616    64.126574    25.854381    1199.210763   
std     8.791521e+06     56.750546    41.467058    11.007935   16121.183073   
min     5.300000e+01      1.000000  -157.948486   -41.330428       0.000000   
25%     3.019625e+05      1.000000    77.081343    28.478713     250.000000   
50%     6.004089e+06      1.000000    77.191964    28.570469     400.000000   
75%     1.835229e+07      1.000000    77.282006    28.642758     700.000000   
max     1.850065e+07    216.000000   174.832089    55.976980  800000.000000   

       Price_Range       Rating         Votes  
count  9551.000000  9551.000000   9551.000000  
mean      1.804837     2.666370    156.909748  
std       0.905609     1.516378    430.169145  
min       1.000000     0.000000      0.000000  
25%       1.000000     2.500000      5.000000  
50%       2.000000     3.200000     31.000000  
75%       2.000000     3.700000    131.000000  
max       4.000000     4.900000  10934.000000

In [10]:
RestaurantRating_data_frame['Currency'].value_counts()

Indian Rupees(Rs.)        8652
Dollar($)                  482
Pounds(��)                  80
Brazilian Real(R$)          60
Emirati Diram(AED)          60
Rand(R)                     60
NewZealand($)               40
Turkish Lira(TL)            34
Botswana Pula(P)            22
Indonesian Rupiah(IDR)      21
Sri Lankan Rupee(LKR)       20
Qatari Rial(QR)             20
Name: Currency, dtype: int64

In [11]:
RestaurantRating_data_frame['Currency'].unique()

array(['Botswana Pula(P)', 'Brazilian Real(R$)', 'Dollar($)',
       'Emirati Diram(AED)', 'Indian Rupees(Rs.)',
       'Indonesian Rupiah(IDR)', 'NewZealand($)', 'Pounds(��)',
       'Qatari Rial(QR)', 'Rand(R)', 'Sri Lankan Rupee(LKR)',
       'Turkish Lira(TL)'], dtype=object)

In [12]:
RestaurantRating_data_frame['Rating'].unique()

array([4.8, 4.5, 4.4, 4.9, 4. , 4.2, 4.3, 3.6, 4.7, 3. , 3.8, 3.7, 3.2,
       3.1, 0. , 4.1, 3.3, 4.6, 3.9, 3.4, 3.5, 2.2, 2.9, 2.4, 2.6, 2.8,
       2.1, 2.7, 2.5, 1.8, 2. , 2.3, 1.9])

In [13]:
numerical_features=[feature for feature in RestaurantRating_data_frame.columns if RestaurantRating_data_frame[feature].dtypes!='O']
numerical_features

['Restaurant ID',
 'Country Code',
 'lon',
 'lat',
 'cost_for_two',
 'Price_Range',
 'Rating',
 'Votes']

In [14]:
# summary of numerical columns
RestaurantRating_data_frame.describe().T

count          mean           std         min            25%  \
Restaurant ID  9551.0  9.051128e+06  8.791521e+06   53.000000  301962.500000   
Country Code   9551.0  1.836562e+01  5.675055e+01    1.000000       1.000000   
lon            9551.0  6.412657e+01  4.146706e+01 -157.948486      77.081343   
lat            9551.0  2.585438e+01  1.100794e+01  -41.330428      28.478713   
cost_for_two   9551.0  1.199211e+03  1.612118e+04    0.000000     250.000000   
Price_Range    9551.0  1.804837e+00  9.056088e-01    1.000000       1.000000   
Rating         9551.0  2.666370e+00  1.516378e+00    0.000000       2.500000   
Votes          9551.0  1.569097e+02  4.301691e+02    0.000000       5.000000   

                        50%           75%           max  
Restaurant ID  6.004089e+06  1.835229e+07  1.850065e+07  
Country Code   1.000000e+00  1.000000e+00  2.160000e+02  
lon            7.719196e+01  7.728201e+01  1.748321e+02  
lat            2.857047e+01  2.864276e+01  5.597698e+01  
cost_for_two   4.000000e+02  7.000000e+02  8.000000e+05  
Price_Range    2.000000e+00  2.000000e+00  4.000000e+00  
Rating         3.200000e+00  3.700000e+00  4.900000e+00  
Votes          3.100000e+01  1.310000e+02  1.093400e+04

In [15]:
RestaurantRating_data_frame.isnull().sum()

Restaurant ID           0
Restaurant_Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
lon                     0
lat                     0
Cuisines                9
cost_for_two            0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price_Range             0
Rating                  0
Rating color            0
Review                  0
Votes                   0
dtype: int64

In [16]:
RestaurantRating_data_frame.dtypes

Restaurant ID             int64
Restaurant_Name          object
Country Code              int64
City                     object
Address                  object
Locality                 object
Locality Verbose         object
lon                     float64
lat                     float64
Cuisines                 object
cost_for_two              int64
Currency                 object
Has Table booking        object
Has Online delivery      object
Is delivering now        object
Switch to order menu     object
Price_Range               int64
Rating                  float64
Rating color             object
Review                   object
Votes                     int64
dtype: object

In [17]:
#Removing the Duplicates
RestaurantRating_data_frame.duplicated().sum()


0

In [18]:
RestaurantRating_data_frame.drop_duplicates(inplace=True)

In [19]:
RestaurantRating_data_frame.shape

(9551, 21)

In [20]:
pip install seaborn

  Using cached numpy-1.21.6-cp37-cp37m-win_amd64.whl (14.0 MB)
  Attempting uninstall: numpy
    Found existing installation: numpy 1.16.5
    Uninstalling numpy-1.16.5:
      Successfully uninstalled numpy-1.16.5
Note: you may need to restart the kernel to use updated packages.


ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'c:\\users\\hpr\\anaconda3\\envs\\rest_rating\\lib\\site-packages\\~-mpy\\.libs\\libopenblas.TXA6YQSD3GCQQC22GEQ54J2UDCXDXHWN.gfortran-win_amd64.dll'
Consider using the `--user` option or check the permissions.



In [21]:
numerical_features=[feature for feature in RestaurantRating_data_frame.columns if RestaurantRating_data_frame[feature].dtypes!='O']
numerical_features

['Restaurant ID',
 'Country Code',
 'lon',
 'lat',
 'cost_for_two',
 'Price_Range',
 'Rating',
 'Votes']

In [22]:
import os
os.getcwd()

'c:\\Users\\HPr\\Restaurant_Rating_prediction'

In [23]:
model_config_file = r"C:\Users\HPr\Restaurant_Rating_prediction\config\model.yaml"

In [24]:
from RestaurantRating.entity.model_factory import ModelFactory

In [25]:
model_factory = ModelFactory(model_config_path=model_config_file)

In [26]:
model_list= model_factory.get_initialized_model_list()


{'fit_intercept': True}
{'min_samples_leaf': 2}


In [27]:
len(model_list)

2

In [28]:
model_list[0]

InitializedModelDetail(model_serial_number='module_0', model=LinearRegression(), param_grid_search={'fit_intercept': [True, False]}, model_name='sklearn.linear_model.LinearRegression')

In [29]:
model_list[1]

InitializedModelDetail(model_serial_number='module_1', model=RandomForestRegressor(min_samples_leaf=2), param_grid_search={'min_samples_leaf': [2]}, model_name='sklearn.ensemble.RandomForestRegressor')

In [30]:
from RestaurantRating.util.util import load_numpy_array_data

In [31]:
data_file_path= r"C:\Users\HPr\Restaurant_Rating_prediction\RestaurantRating\artifact\data_transformation\2023-01-17-18-44-16\transformed_data\train\Zomato_csv.npz"

In [32]:
data_file_path

'C:\\Users\\HPr\\Restaurant_Rating_prediction\\RestaurantRating\\artifact\\data_transformation\\2023-01-17-18-44-16\\transformed_data\\train\\Zomato_csv.npz'

In [33]:
pip install numpy==1.16.1


  Using cached numpy-1.16.1-cp37-cp37m-win_amd64.whl (11.9 MB)
  Attempting uninstall: numpy
    Found existing installation: numpy 1.21.6
    Uninstalling numpy-1.21.6:
      Successfully uninstalled numpy-1.21.6
Note: you may need to restart the kernel to use updated packages.


ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
statsmodels 0.13.5 requires numpy>=1.17; python_version != "3.10" or platform_system != "Windows" or platform_python_implementation == "PyPy", but you have numpy 1.16.1 which is incompatible.
seaborn 0.12.2 requires numpy!=1.24.0,>=1.17, but you have numpy 1.16.1 which is incompatible.
scipy 1.7.3 requires numpy<1.23.0,>=1.16.5, but you have numpy 1.16.1 which is incompatible.
matplotlib 3.5.3 requires numpy>=1.17, but you have numpy 1.16.1 which is incompatible.
evidently 0.2.1 requires numpy>=1.19.5, but you have numpy 1.16.1 which is incompatible.


In [34]:
import numpy as np
data = load_numpy_array_data(data_file_path)

In [35]:
x,y=data[:,:-1],data[:,-1]


In [36]:
best_model= model_factory.get_best_model(x,y)


{'fit_intercept': True}
{'min_samples_leaf': 2}
{'cv': 2, 'verbose': 2}
Fitting 2 folds for each of 2 candidates, totalling 4 fits


RestaurantRatingException: 
        Error occured in script: 
        [ c:\Users\HPr\Restaurant_Rating_prediction\RestaurantRating\entity\model_factory.py ] at 
        try block line number: [366] and exception block line number: [371] 
        error message: [
        Error occured in script: 
        [ c:\Users\HPr\Restaurant_Rating_prediction\RestaurantRating\entity\model_factory.py ] at 
        try block line number: [319] and exception block line number: [324] 
        error message: [
        Error occured in script: 
        [ c:\Users\HPr\Restaurant_Rating_prediction\RestaurantRating\entity\model_factory.py ] at 
        try block line number: [304] and exception block line number: [306] 
        error message: [
        Error occured in script: 
        [ c:\Users\HPr\Restaurant_Rating_prediction\RestaurantRating\entity\model_factory.py ] at 
        try block line number: [239] and exception block line number: [250] 
        error message: [Cannot have number of splits n_splits=2 greater than the number of samples: n_samples=1.]
        ]
        ]
        ]
        

In [ ]:
x.shape

(1, 49395)

In [ ]:
y

array([3.4], dtype=object)

In [ ]:
import pandas as pd
y_DATA= pd.DataFrame(y)
y_DATA

0
0  3.4

In [ ]:
import pandas as pd
data_array= pd.DataFrame(data)
data_array.head()[0]

0      (0, 0)\t-0.006154384387507251\n  (0, 1)\t1.3...
Name: 0, dtype: object

In [ ]:
x=data_array[0]

In [ ]:
data_array[0][1]


TypeError: cannot concatenate object of type '<class 'numpy.ndarray'>'; only Series and DataFrame objs are valid

In [ ]:
y

array([4.8, 4.5, 4.4, ..., 3.7, 4. , 4. ])

In [ ]:
new_data= pd.DataFrame(x,y,columns=x,y)

SyntaxError: positional argument follows keyword argument (1375137174.py, line 1)

In [ ]:
best_model= model_factory.get_best_model(x,y)

{'fit_intercept': True}
{'min_samples_leaf': 2}
{'cv': 4, 'verbose': 2}


RestaurantRatingException: 
        Error occured in script: 
        [ c:\Users\HPr\Restaurant_Rating_prediction\RestaurantRating\entity\model_factory.py ] at 
        try block line number: [364] and exception block line number: [369] 
        error message: [
        Error occured in script: 
        [ c:\Users\HPr\Restaurant_Rating_prediction\RestaurantRating\entity\model_factory.py ] at 
        try block line number: [317] and exception block line number: [322] 
        error message: [
        Error occured in script: 
        [ c:\Users\HPr\Restaurant_Rating_prediction\RestaurantRating\entity\model_factory.py ] at 
        try block line number: [302] and exception block line number: [304] 
        error message: [
        Error occured in script: 
        [ c:\Users\HPr\Restaurant_Rating_prediction\RestaurantRating\entity\model_factory.py ] at 
        try block line number: [237] and exception block line number: [248] 
        error message: [Found input variables with inconsistent numbers of samples: [2, 9551]]
        ]
        ]
        ]
        

In [ ]:
data1=r'C:\Users\HPr\Restaurant_Rating_prediction\RestaurantRating\artifact\data_ingestion\2023-01-17-19-22-29\raw_data\Zomato_csv.csv'

In [ ]:
df=pd.read_csv(data1)

In [ ]:
df

online_order  book_table      rate  votes  rest_type  cuisines    cost  \
0                 1           1  4.100000    775         27      2091   800.0   
1                 1           0  4.100000    787         27       922   800.0   
2                 1           0  3.800000    918         22       743   800.0   
3                 0           0  3.700000     88         78      2469   300.0   
4                 0           0  3.800000    166         27      2119   600.0   
...             ...         ...       ...    ...        ...       ...     ...   
49390             0           0  3.600000     27          8       977  1500.0   
49391             0           0  3.700449      0          8      1346   600.0   
49392             0           0  3.700449      0          8      1346  2000.0   
49393             0           1  4.300000    236          8      1346  2500.0   
49394             0           0  3.400000     13         10      1371  1500.0   

       menu_item  type  city  
0           8778     0     1  
1           8778     0     1  
2           8778     0     1  
3           8778     0     1  
4           8778     0     1  
...          ...   ...   ...  
49390       8778     6    29  
49391       8778     6    29  
49392       8778     6    29  
49393       8778     6    29  
49394       8778     6    29  

[49395 rows x 10 columns]

In [ ]:
df['rate'].shape

(49395,)

In [ ]:
from RestaurantRating.component.data_transformation import DataTransformation
train_file_path = r"C:\Users\HPr\Restaurant_Rating_prediction\RestaurantRating\artifact\data_ingestion\2023-01-17-20-08-46\ingested_data\train\Zomato_csv.csv"

In [ ]:
from RestaurantRating.util.util import load_data,read_yaml_file
schema_file_path=r"C:\Users\HPr\Restaurant_Rating_prediction\config\schema.yaml"

In [ ]:
train_df = load_data(file_path=train_file_path, schema_file_path=schema_file_path)

In [ ]:
train_df

online_order  book_table      rate  votes  ...    cost  menu_item  type  city
0                 1           1  4.100000    775  ...   800.0       8778     0     1
1                 1           0  4.100000    787  ...   800.0       8778     0     1
2                 1           0  3.800000    918  ...   800.0       8778     0     1
3                 0           0  3.700000     88  ...   300.0       8778     0     1
4                 0           0  3.800000    166  ...   600.0       8778     0     1
...             ...         ...       ...    ...  ...     ...        ...   ...   ...
49390             0           0  3.600000     27  ...  1500.0       8778     6    29
49391             0           0  3.700449      0  ...   600.0       8778     6    29
49392             0           0  3.700449      0  ...  2000.0       8778     6    29
49393             0           1  4.300000    236  ...  2500.0       8778     6    29
49394             0           0  3.400000     13  ...  1500.0       8778     6    29

[49395 rows x 10 columns]

In [ ]:
schema = read_yaml_file(file_path=schema_file_path)
schema

{'columns': {'online_order': 'object',
  'book_table': 'object',
  'rate': 'float',
  'votes': 'int',
  'type': 'object',
  'rest_type': 'int',
  'cuisines': 'int',
  'cost': 'int',
  'menu_item': 'object',
  'city': 'object'},
 'numerical_columns': ['votes', 'cost', 'rest_type'],
 'categorical_columns': ['cuisines',
  'online_order',
  'book_table',
  'menu_item',
  'city',
  'type'],
 'target_column': 'rate'}

In [ ]:
from RestaurantRating.constant import *

In [ ]:
target_column_name = schema[TARGET_COLUMN_KEY]
target_column_name

'rate'

In [ ]:
input_feature_train_df = train_df.drop(columns=[target_column_name],axis=0)
input_feature_train_df

online_order  book_table  votes  ...  menu_item  type  city
0                 1           1    775  ...       8778     0     1
1                 1           0    787  ...       8778     0     1
2                 1           0    918  ...       8778     0     1
3                 0           0     88  ...       8778     0     1
4                 0           0    166  ...       8778     0     1
...             ...         ...    ...  ...        ...   ...   ...
49390             0           0     27  ...       8778     6    29
49391             0           0      0  ...       8778     6    29
49392             0           0      0  ...       8778     6    29
49393             0           1    236  ...       8778     6    29
49394             0           0     13  ...       8778     6    29

[49395 rows x 9 columns]

In [ ]:
target_feature_train_df = train_df[target_column_name]
target_feature_train_df

0        4.100000
1        4.100000
2        3.800000
3        3.700000
4        3.800000
           ...   
49390    3.600000
49391    3.700449
49392    3.700449
49393    4.300000
49394    3.400000
Name: rate, Length: 49395, dtype: float64

In [37]:
train_file_path=r"C:\Users\HPr\Restaurant_Rating_prediction\RestaurantRating\artifact\data_transformation\2023-01-18-19-48-13\transformed_data\train\Zomato_csv.npz"

In [46]:
array_data=load_numpy_array_data(train_file_path)
array_data.shape

(1, 49396)

In [47]:
test_file_path=r"C:\Users\HPr\Restaurant_Rating_prediction\RestaurantRating\artifact\data_transformation\2023-01-18-19-48-13\transformed_data\test\Zomato_csv.npz"

In [48]:
array_test_data=load_numpy_array_data(test_file_path)

In [49]:
array_test_data.shape

(1, 49396)

In [50]:
x_train,y_train,x_test,y_test = array_data[:,:-1],array_data[:,-1],array_test_data[:,:-1],array_test_data[:,-1]


In [53]:
x_train.shape

(1, 49395)

In [54]:
y_train.shape

(1,)

In [55]:
y_train

array([3.4], dtype=object)

In [57]:
x_test.shape

(1, 49395)

In [58]:
y_test.shape

(1,)

In [59]:
array_test_data[:,-1]

array([3.4], dtype=object)

In [62]:
array_test_data[:,:-1].shape

(1, 49395)